[build]
  command = "npm run build"
  publish = "out"

[functions]
    node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"